### PR TITLE
621 - Theming

### LINKED ISSUE #621: Add Light/Dark theme support in the FRB Editor
This would allow the user to swap between light/dark theme, just like in Visual Studio and many other apps.

## Current Progress

Most of the FlatRedBall UI is now WPF, which means it can be themed. The light and dark themes are defined in Light.xaml and Dark.xaml 

image

To pick which is used:

1. Open MainPanelControl.xaml and change the ResourceDictionary to have the following:
```
<UserControl.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="/Themes/Dark.xaml" />
            <!--<ResourceDictionary Source="/Themes/Light.xaml" />-->
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</UserControl.Resources>

```
2. Open MainPanelControl.xaml.cs and change the AppTheme to "Dark"
```
 public partial class MainPanelControl : UserControl
 {
     #region Fields/Properties

     public static string AppTheme = "Dark";
     public static ResourceDictionary ResourceDictionary { get; private set; }
     public static bool IsExiting { get; private set; }
     ...
```
3. Build and run FRB Editor (Glue)

Note, currently there is a lot of extra work that needs to be done to use this theme. For example, the following shows what the editor looks like using the Dark theme as of June 27, 2022:

image

There are a few things that are causing this theme to draw incorrectly:

1. Some controls are still winforms (like Output text box)
2. Some controls are using hardcoded values such as the alternating colors in the WPF Data Grid
3. Some controls are custom and not using any styling, such as the treeview.
4. Some controls have manually set colors based on their state, such as toggle buttons.

### PR DESCRIPTION
**Pull request by vicdotexe**
Fixes: #621

This will start as a draft for user testing.

Testers: 
- Make sure you have latest version of Gum pulled and built. 
- Make sure to rebuild the entire solution as there have been changes made to plugin projects that aren't rebuilt when running glue (you should make habit to do this every time you pull any new changes)

**From the top menu strip, `Settings -> Theming` will bring up the theming window.**

I need help finding things areas that I haven't explored yet, as I'm not familiar with most features/aspects of the app and touched only the most obvious surfaces.

Please help me find:
- Lingering buttons which are still using icons generic enough to be replaced with [these material design icons](https://pictogrammers.com/library/mdi/)
- Areas which still appear to have hard coded colors that conflict with the theming changes.
- General visual fallout from the change, including: layout, padding, margin, size, unresponsive/unfit colors, etc.
- Any possibly functionality issues or visual inconsistencies specifically with DataGrids and ComboBoxes, as these controls have been re-templated, but the depth at which they need to be is currently unknown to me.

Use this PR as a place to communicate your findings, with screenshots and descriptions.

Thank you!

### CODE REVIEW

**Comment by vchelaru** [comment]
Cut-off text in combo boxes when adding a new level screen.

image

**Comment by vchelaru** [comment]
Search has become nearly unusable for medium-sized projects like Cranky Chibi Cthulhu. I move the cursor in a circle whenever waiting for typing or removal of search to give you an idea of how long it takes.

**Comment by vchelaru** [comment]
Unused drop-down icon next to camera icon should be removed. I don't remember if this was in the old FRB Editor, but if it was we should still remove it if it's easy to do.

image

**Comment by vchelaru** [comment]
GroupBox Header gets cut-off when squashing right-side quick action tab horizontally.

**Comment by vicdotexe** [comment]
> Unused drop-down icon next to camera icon should be removed. I don't remember if this was in the old FRB Editor, but if it was we should still remove it if it's easy to do.

@vchelaru 
I had originally made a brief attempt to address this until I realized it is existing behavior (as can be seen in multiple screenshots from [this tutorial](https://docs.flatredball.com/flatredball/tutorials/beefball/creating-a-glue-project#opening-and-running-your-project)). There are two issues here: 
1. It even shows up at all when there is no overflow
3. When it does show up it doesn't match the theming. 

I am ok with taking a stab at addressing the latter as part of this PR, however I do recall it being a bit in the weeds.

**Comment by vicdotexe** [comment]
> Cut-off text in combo boxes when adding a new level screen.

@vchelaru 
fixed

**Comment by mfigueirido** [comment]
Maybe nitpicking but I would give the loader screen more breathing room at the edges:

imaxe

Great job with the restyling!

**Comment by mfigueirido** [comment]
Pressing any keyboard key or hovering over any of the panels instantly crashes the app for me:
imaxe

Edit: It only happens when running the compiled EXE. If I run through Visual Studio, it works fine...

**Comment by mfigueirido** [comment]
Selecting a bookmark no longer brings into view the related panel.

For example, I have a bookmark pointing to the variables section of an entity, but clicking it doesn't bring into view the corresponding "variables" panel.

imaxe

This is what should look like:
imaxe

It happens with other types of nodes too. Selecting a variable should bring into view the properties panel:
imaxe

**Comment by mfigueirido** [comment]
This was mentioned by @vchelaru previously, but I want to confirm search is super slow now. Previously it was near instant, now it takes several seconds to show the results. The same for clearing them (pressing the "x" at the right side).

**Comment by mfigueirido** [comment]
Another nitpick. The degrees symbol appears cut off.
imaxe

**Comment by mfigueirido** [comment]
The slowness can also be felt when the variables panel of a large entity is brought into view. Instant previously, now has a lag of around a second for this entity with 68 variables. 

https://github.com/user-attachments/assets/14622cfc-9f9d-40b6-ba36-2be305033829

Note: the click actually happens before the node's control is in "selected" state.

**Comment by mfigueirido** [comment]
Panels no longer carry over the previous session width/height.

Before closing the app:
imaxe

Opening again:
imaxe

Edit: Switched to the latest NetStandard and this is broken there too, so it looks like something recent but not because of this PR.

**Comment by vchelaru** [comment]
~If you create a Polygon object in a Screen or entity, select it, then click on the Points tab, the icon buttons have a blue background which makes it hard to see the point icons~

image

I fixed this with 92706c3e436ab9b5e351ae6085eb17bfa0b5c012

**Comment by vchelaru** [comment]
Categories with no names still allow you to expand/collapse but they should not.

This is how it worked in the old styling:

image

This is the new:

image

**Comment by vchelaru** [comment]
Running the game in edit mode should show buttons with the new styling. I can fix this easily by giving them the proper style, but I don't know if you also wanted to change the way the speed UI works, or if you wanted to change icons. 

image

**Comment by vicdotexe** [comment]
@vchelaru  @mfigueirido 
I've pushed a fix for the poor performance with the searchbox (and most likely variables tab @mfigueirido could you verify this part?), this was actually caused by the scrollbar implementation and that has now been replaced.

**Comment by vicdotexe** [comment]
> Categories with no names still allow you to expand/collapse but they should not.

@vchelaru 
Is this behavior expected for all expander controls or just in this tab?

**Comment by vicdotexe** [comment]
> Maybe nitpicking but I would give the loader screen more breathing room at the edges:

@mfigueirido 
This was not something I touched, my guess is it feels more noticeable after I removed the window frame. However I agree with you, and it's an easy enough change, which is now pushed.

**Comment by vicdotexe** [comment]
> Running the game in edit mode should show buttons with the new styling. I can fix this easily by giving them the proper style, but I don't know if you also wanted to change the way the speed UI works, or if you wanted to change icons.

@vchelaru 
I went ahead and tuned that up. Outside of swapping the icons, I slightly changed the toggle setup you had to make it a little more contained/apparent, and moved the speed settings to the right of all the otherwise more-related action buttons. 

Outside of the scope of this PR, while I was here I also updated the way the "disabled edit-mode message" is communicated, from the pretty invasive message box to an orange informational quick-tooltip icon, hope you're ok with that.

**Comment by vchelaru** [comment]
Dark mode output window should display white and red text instead of black and red text. Note that error output does print in red

image

**Comment by vicdotexe** [comment]
> Categories with no names still allow you to expand/collapse but they should not.

Addressed this in a [PR to Gum](https://github.com/vchelaru/Gum/pull/183)

**Comment by vicdotexe** [comment]
> Pressing any keyboard key or hovering over any of the panels instantly crashes the app for me
> Edit: It only happens when running the compiled EXE. If I run through Visual Studio, it works fine...

@mfigueirido 
I was able to produce a similar crash, although not through your exact steps (mine was instantaneous after the initialization screen). I believe I've fixed it in my recent commit, related to hosting WPF inside WinForms. I attempted to follow your reproduction steps after the fix and was unable to reproduce, could you try again with the recent change?

**Comment by vicdotexe** [comment]
> Another nitpick. The degrees symbol appears cut off.

@mfigueirido 
Once [this PR to Gum](https://github.com/vchelaru/Gum/pull/184) merges, this will be fixed.

**Comment by vicdotexe** [comment]
> GroupBox Header gets cut-off when squashing right-side quick action tab horizontally.

@vchelaru 
I've gone with a completely new group box implementation which fixes this.

**Comment by vicdotexe** [comment]
> Dark mode output window should display white and red text instead of black and red text. Note that error output does print in red

@vchelaru 
[fixed](https://github.com/vchelaru/FlatRedBall/pull/1477/commits/926a649f38b21a39cda2bdc4847fd51d77402c8d) (this implementation was better than my first attempt with the output tab, so I adjusted that as well)

**Comment by mfigueirido** [comment]
@vicdotexe
Made a few tests regarding the stuff I reported and to summarize:

1. Fix confirmed for slowness when searching and lag when showing variables.
2. Fix confirmed for crashes at startup or when interacting with the panels.
3. Loader screen is pretty now.
4. Degrees symbol should be fixed with Gum's PR.

Things remaining:
1. Bring into view default panel for each tree node type.
2. Carry over width/height for panels between sessions.

**Comment by mfigueirido** [comment]
I would ask for a couple more things if possible, these are really small stuff :)

1. Make the screen control larger so bigger screen names fit.
imaxe
2. Enable mouse middle button scrolling for screen and tile map drop-downs:
imaxe
imaxe
I believe this was working in the previous UI and benefits projects with tons of screens/tmx files.

**Comment by vicdotexe** [comment]
Issue tracking has been moved to discord

**Pull request merged**
